#!/bin/bash

end=${1:-0}
cd $(dirname $0)/..

echo "# Autogenerated">type-1.tf
for i in $(seq -f "%03g" 0 $end); do
cat >> type-1.tf<<EOF
module "type_1_$i" {
  source      = "./modules/nodes"
  name        = "type-1-$i"
  aws_profile = "\${var.aws_profile}"
  aws_region  = "\${var.aws_region}"
  ssh_key_id  = "\${aws_key_pair.nodes.id}"
  subnets     = "\${data.aws_subnet.available.*.id}"
  vpc         = "\${data.aws_vpc.default.id}"
  os          = "rancheros"
  image_id    = "\${data.aws_ami.rancheros.id}"
  sg          = "\${aws_security_group.nodes.id}"
}
EOF
done
